# Generated by Django 3.0.5 on 2020-04-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_imagealbum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('images', models.ManyToManyField(blank=True, to='gallery.Image')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageAlbum',
        ),
    ]
