# Generated by Django 3.0.5 on 2020-04-16 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20200415_0310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='album',
            name='highlight',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.Image'),
        ),
        migrations.AlterField(
            model_name='album',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='image_albums', to='gallery.Image'),
        ),
    ]
